CREATE TABLE IF NOT EXISTS model_configs (
  id SMALLINT PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  provider TEXT NOT NULL DEFAULT 'OPENAI',
  model TEXT NOT NULL DEFAULT 'gpt-5.4',
  base_url TEXT NOT NULL DEFAULT 'http://43.172.5.210:3000/v1',
  api_key TEXT NOT NULL DEFAULT '',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
