ALTER TABLE reading_materials ADD COLUMN IF NOT EXISTS band DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE reading_materials ADD COLUMN IF NOT EXISTS stage TEXT NOT NULL DEFAULT '';
ALTER TABLE reading_materials ADD COLUMN IF NOT EXISTS section TEXT NOT NULL DEFAULT '';
ALTER TABLE reading_materials ADD COLUMN IF NOT EXISTS skill_focus TEXT NOT NULL DEFAULT '';
ALTER TABLE reading_materials ADD COLUMN IF NOT EXISTS question_type TEXT NOT NULL DEFAULT '';
ALTER TABLE reading_materials ADD COLUMN IF NOT EXISTS scenario_family TEXT NOT NULL DEFAULT '';
